version: "3"
services:
  polls_server:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - pq_db
  pq_db:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=******
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5436:5432"
